version: '3.8'

services:
    sub-one:
        image: ghcr.io/binbankm/sub-one:latest
        container_name: sub-one
        ports:
            - '3055:3055'
        volumes:
            - ./data:/app/data
        restart: unless-stopped
        environment:
            - PORT=3055
            - TZ=Asia/Shanghai
